fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "kontakt@tomicom.pl"
        sender_name: "Biuro Obslugi Klienta :: TomiCom"
